name: PaaS Demo

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'
    # only build when important files change
    #paths:
    #  - 'app'
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    #paths:
    #  - 'app'
      
permissions:
  id-token: write
  contents: read

env:
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  call-waypoint-up:
    name: Publish the app
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v1
        with:
          #client-id: ${{ secrets.AZURE_CLIENT_ID }}
          #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          
      - name: 'Checkout the branch'
        uses: actions/checkout@v2
        
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP_NAME }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
      
      - name: Install kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      #- name: 'Login to Docker registry'
      #  run: docker login --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Install Waypoint'
        run: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
             echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list && \
             sudo apt update && sudo apt install waypoint

      - name: 'Create context'
        run: |
          waypoint context create \
          -server-addr=api.hashicorp.cloud:443 \
          -server-auth-token=${{ secrets.WAYPOINT_SERVER_TOKEN }} \
          -server-require-auth=true \
          -server-platform="hcp" \
          -set-default \
          hcp-cderue-org-cderue-project
          
      - name: 'Publish with Waypoint'
        run: |
          waypoint init
          waypoint up
